### ISSUE TITLE
Request: Update this on e107

### ISSUE THREAD

**Issue by LaocheXe** [Moc/wrapper#10]
Can you release the updated version of this on e107? The version I downloaded didn't have e_PAGETITLE in wrapper.php

**Comment by Moc** [comment]
Will check it

**Comment by Moc** [comment]
Which version do you have installed/downloaded from e107.org/Find Plugins in the admin area?

**Comment by LaocheXe** [comment]
not 100% sure since updated from here. It was installed from Fine Plugins part in admin area - had it since 2/3 years - if there was an update, I would have been notified in e107 admin area, but haven't for Wrapper plugin. (gotten it a few times with various plugins).

**Comment by LaocheXe** [comment]
Just remember I have a backup - it's version 1.1.0  for the wrapper plugin

**Comment by Moc** [comment]
I just tried this and for me it only shows the latest version (1.2.0): 
![image](https://user-images.githubusercontent.com/577978/84239187-69b26180-aafc-11ea-9d1a-2c131f42c2d0.png)

When did you install the plugin? Before february 2019? If yes, then the issue would indeed be that it didn't show the update in e107.org. 

@CaMer0n any ideas?

**Comment by LaocheXe** [comment]
Then it must be an cache issue on my end. Because now inside Plugin Manager > Installed - it's telling me there is an update for the Wrapper plugin, however it's already been updated via ftp.

When clicking on it I get something weird, which might be either e107 issue, or something on the server causing this.

![Annotation 2020-06-10 073236](https://user-images.githubusercontent.com/5818022/84268067-b68e3c00-aaec-11ea-9818-976502e47528.png)

**Comment by Moc** [comment]
Id'definitely clear all caches (including browser cache) and see if that resolves it.

**Comment by LaocheXe** [comment]
Done

**Comment by CaMer0n** [comment]
@Moc If you have an old version of the wrapper plugin, I'd be happy to try it here and see if an upgrade alert comes through.

**Comment by Moc** [comment]
@CaMer0n They're all listed here: https://github.com/Moc/wrapper/releases
I just installed 1.1.0 (which is NOT the latest), but I do not get an update notification for 1.2.0. 

in e107.org addons I see: 

![image](https://user-images.githubusercontent.com/577978/84892460-e960a300-b09d-11ea-9ab3-2306a61cd850.png)
