### ISSUE TITLE
PHP 8 error. 

### ISSUE THREAD

**Issue by CaMer0n** [Moc/wrapper#11]
Just fyi

Fatal error: Declaration of wrapper_ui::beforeCreate($new_data) must be compatible with e_admin_ui::beforeCreate($new_data, $old_data) in W:\www\e107v2\e107_plugins\wrapper\admin_config.php on line 111

**Comment by Moc** [comment]
Thanks, will do testing with PHP 8 and fix this one as well.

**Comment by Moc** [comment]
@CaMer0n Done. New release (1.3.0) uploaded and approved on e107.org

**Comment by CaMer0n** [comment]
@Moc Great! :+1:
