### ISSUE TITLE
FR - allow more options for plugin itself

### ISSUE THREAD

**Issue by Jimmi08** [Moc/wrapper#18]

**Comment by Moc** [comment]
@Jimmi08 What kind of options are you looking for?

**Comment by Jimmi08** [comment]
I am working it, just I had to do domething else

Dňa ne, 3. júl 2022, 16:15 Tijn Kuyper ***@***.***>
napísal(a):

**Comment by Moc** [comment]
I could save you time if you give me a description :) otherwise you may perhaps end up making something that I won't integrate into the plugin....

**Comment by Jimmi08** [comment]
Hi,
it is not problem if it is not integrated.  I have it already.  

It is better if you see it,   I disliked 3 db query for the same thing 

First one:
Set title off - if included URL has title already - but this can be fixed with special layout or tablerender.

Others are planned. Next weekend maybe.

**Comment by Moc** [comment]
I am closing this. Please see my latest changes and then submit new SEPARATE issues with new feature requests so I can review them.
