### ISSUE TITLE
Feature Request: Global shortcode {WRAPPER=x}

### ISSUE THREAD

**Issue by CaMer0n** [Moc/wrapper#5]
This would remove the need for SEF Urls as the existing SEFs from News, Pages etc could be used. 
I believe moving the main code from wrapper.php into a class would make this quite simple.

**Comment by Moc** [comment]
This has now been implemented and will be included in the 1.1.0 release. Documentation have also been updated: https://github.com/Moc/wrapper/wiki/Functionalities#shortcode
