### ISSUE TITLE
Says SURVEYS in tab

### ISSUE THREAD

**Issue by Norwayman** [Moc/wrapper#7]
![tabsayssurveys](https://user-images.githubusercontent.com/1757346/28333300-1bb9b630-6bbd-11e7-86f3-c30bc597ca38.JPG)

I am using the Wrapper plugin to show a timeline I found. But if you se in the TAB for this page it says Surveys. I have been looking all over the place for where I can change this. Can you help me?

https://www.riocascadamedia.com/e107_plugins/wrapper/wrapper.php?1

**Comment by Moc** [comment]
What is the title you entered in the Wrapper Admin Area?

**Comment by Norwayman** [comment]
![titles](https://user-images.githubusercontent.com/1757346/28380163-eb27e054-6c7b-11e7-99b4-f3c25d02204b.JPG)

@Moc These are the titles. Nothing to do with SURVEYS as it says in the TAB :)
And inside these HTML files there is nothing saying "SURVEYS" either.

**Comment by Moc** [comment]
Very interesting.. I'm on vacation atm but will take a look once I'm back on my laptop

**Comment by Moc** [comment]
Which will be early august :)

**Comment by Norwayman** [comment]
@Moc Oh sorry....didn't know you were on vacation. Have a good one and see you in August! :)

**Comment by Moc** [comment]
No worries, no way you could know. I shouldn't be replying haha :p thanks!

**Comment by Moc** [comment]
Are you using the Survey plugin actively? If not, please uninstall. Does the proper title now display instead?

**Comment by Norwayman** [comment]
@Moc Yes I am using the Survey plugin (Git 2.1 version from Jimako) It has som changes that I tested and I really love that plugin. I uninstalled it now, and guess what? This is the result:

![newtabscreenshot](https://user-images.githubusercontent.com/1757346/28726627-9110f976-7387-11e7-86aa-4e4b5af857ea.JPG)

**Comment by Norwayman** [comment]
So I guess it worked with your prediction. BUT....it still doesn't show title in the tab. Just the name of my homepage. :)

**Comment by Moc** [comment]
Yeah still no good. You can reinstall the survey plugin and use it again. 
I'll see if I can make some tweaks this weekend. Thanks for the quick feedback.

**Comment by Norwayman** [comment]
@Moc I also wrote to Jimako to see if there is something. I don't know.....using the same names on variables or somthing.

**Comment by Jimmi08** [comment]
Guys, my mistake. It's result of using survey plugin for company that I needed it for. I didn't plan to publish it, but later I decided to do it and  I thought I stripped all custom things  (in this case not working / weird working  e_PAGETITLE, so I hardcoded it).   That site uses only this one plugin and it's called survey so I didn't notice it.

@Norwayman comment please line 26 - 42 in https://github.com/Jimmi08/survey/blob/master/e_header.php

That code should be executed only if you are on survey pages but I am not able to fix it now. And it's always tricky with sef-url version, so I am not able to write code directly.

**Comment by Norwayman** [comment]
@Jimmi08 @Moc Yes Jimako's solution worked. Now, everything will be perfect if Moc gets his title done for the tabs :) Thanks guys!

**Comment by Moc** [comment]
See the latest version of wrapper.php: https://github.com/Moc/wrapper/blob/master/wrapper.php
The page title should work properly now. Let me know if it works.

**Comment by Norwayman** [comment]
@moc Yes, it works like a charm now!  Thank you!

**Comment by Moc** [comment]
You're welcome :)
