### ISSUE TITLE
Width is not fullscreen

### ISSUE THREAD

**Issue by Bepo2902** [Moc/wrapper#9]
Hi,

Thank you for updating the wrapper for version 2. 
I just installed the new wrapper. And I noticed that the height works fine when leaving it on "0", but the width is not. It is much smaller than the fullscreen.
See screenshot attached.
![screen](https://user-images.githubusercontent.com/46347624/58461483-b7457180-8127-11e9-8bc0-03436475c7f0.PNG)

**Comment by Moc** [comment]
I've done a lot of testing on several websites, but I cannot get this reproduced really. 
Is the link to the website you are trying to wrap public? If yes, what is it? Then I can try and reproduce it. 

What happens if you set a large number for the width? e.g. 1200?

**Comment by Bepo2902** [comment]
It's solved. I have forgotten to enter the wrapper into "Jumbotron (full width)" in Theme Manager.
Sorry for wasting your time.
